-- MySQL Script generated by MySQL Workbench
-- Sun Apr 30 13:03:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdFuncionarios` DEFAULT CHARACTER SET utf8 ;
USE `bdFuncionarios` ;

-- -----------------------------------------------------
-- Table `bdFuncionarios`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdFuncionarios`.`Funcionarios` (
  `codFuncionarios` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Rg` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Fone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `DataNas` VARCHAR(45) NOT NULL,
  `codConjuge` VARCHAR(45) NULL,
  `DataReg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codFuncionarios`))
ENGINE = InnoDB
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
